name: projeto_cloud

services:
  db:
    image: postgres
    container_name: db_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-cloud_database}
    ports:
      - "5425:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
  app:
    image: ribs2004/projeto_cloud:latest
    container_name: fast_api_container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-db}:5432/${POSTGRES_DB:-cloud_database}
    depends_on:
      db:
        condition: service_healthy